name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deployment script on remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            if [ -f ~/production-project/.deploy/deploy.sh ]; then
              chmod +x ~/production-project/.deploy/deploy.sh
              ~/production-project/.deploy/deploy.sh
            else
              echo "Deployment script not found!"
              exit 1
            fi
